spain20['CA'] = spain20['CA'].replace('Comunitat Valenciana', 'Comunidad Valenciana')
spain20['CA'] = spain20['CA'].replace('Asturias, Principado de', 'Asturias')
spain20['CA'] = spain20['CA'].replace('Balears, Illes', 'Islas Baleares')
spain20['CA'] = spain20['CA'].replace('Canarias', 'Islas Canarias')
spain20['CA'] = spain20['CA'].replace('Madrid, Comunidad de', 'Comunidad de Madrid')
spain20['CA'] = spain20['CA'].replace('Murcia, Región de', 'Comunidad de Murcia')
spain20['CA'] = spain20['CA'].replace('Navarra, Comunidad Foral de', 'Navarra')
spain20['CA'] = spain20['CA'].replace('Rioja, La', 'Comunidad Valenciana')
spain20['CA'] = spain20['CA'].replace('Castilla-La Mancha', 'Castilla La Mancha')
comprobar(spain20)